## 1. Common data problems

### Data type constraints

Course outline: 

    - Diagnose dirty data
    - Side effects of dirty data
    - Clean data

---------------------------------------------------------------
Data science workflow:

    - Access data
    - Explore and process data
    - Extract insights
    - Report insights

---------------------------------------------------------------
Dirty data: 

    - duplicate values
    - mis-spellings
    - data type parsing error
    - legacy systems

---------------------------------------------------------------
Data type constraints:

    - Text data (str): first name, last name, address
    - Integers (int): #subscribers, #product sold
    - Decimals (float): temperature, $ exchange rates
    - Binary (bool): is married, new customer, yes/no
    - Dates (datetime): order dates, ship dates
    - categories (category): marriage status gender

NOTE: SELALU CEK DATA TYPE DAN INFO DATA SEBELUM MEMULAI SEMUANYA!

#### String to integers

In [6]:
import pandas as pd

sales = pd.read_csv('sales.csv')
sales.head(2)

   salesorderid   revenue  quantity
0         43659   567839$        12
1         45678    12345$        32

In [7]:
# Cek data type columns
print(sales.dtypes)

salesorderid     int64
revenue         object
quantity         int64
dtype: object

In [8]:
# Dataframe information
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   salesorderid  4 non-null      int64
 1   revenue       4 non-null      object
 2   quantity      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [9]:
# Print sum of all revenue column
sales['revenue'].sum()

' 567839$ 12345$ 356788$ 234444$'

In [10]:
# Remove $ from revenue column
sales['revenue'] = sales['revenue'].str.strip('$')
sales['revenue'] = sales['revenue'].astype('int')

In [11]:
# Verify that revenue is now an integer
assert sales['revenue'].dtype == 'int'

#### Numerical or categorical?

In [ ]:
# Convert to categorical type
df['marriage_status'] = df['marriage_status'].astype('category')

In [13]:
ride_sharing = pd.read_csv('ride_sharing_new.csv')
ride_sharing.head()

,Unnamed: 0,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender
0,0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male
1,1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male
2,2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male
3,3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male
4,4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male

In [59]:
ride_sharing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       25760 non-null  int64
 1   duration         25760 non-null  object
 2   station_A_id     25760 non-null  int64
 3   station_A_name   25760 non-null  object
 4   station_B_id     25760 non-null  int64
 5   station_B_name   25760 non-null  object
 6   bike_id          25760 non-null  int64
 7   user_type        25760 non-null  int64
 8   user_birth_year  25760 non-null  int64
 9   user_gender      25760 non-null  object
dtypes: int64(6), object(4)
memory usage: 2.0+ MB

In [60]:
ride_sharing['user_type'].describe()

count    25760.000000
mean         2.008385
std          0.704541
min          1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: user_type, dtype: float64

In [65]:
# Convert user_type from integer to category
ride_sharing['user_type_cat'] = ride_sharing['user_type'].astype('category')

In [66]:
# Cek apakah data type sudah berubah
assert ride_sharing['user_type_cat'].dtype == 'category'

In [67]:
ride_sharing['user_type_cat'].describe()

count     25760
unique        3
top           2
freq      12972
Name: user_type_cat, dtype: int64

#### Summing strings and concatening numbers

In [71]:
# Strip duration of minutes
ride_sharing['duration_trim'] = ride_sharing['duration'].str.strip('minutes')

# Convert duration to integer
ride_sharing['duration_time'] = ride_sharing['duration_trim'].astype('int')

# Cek
assert ride_sharing['duration_time'].dtype == 'int'

print(ride_sharing[['duration', 'duration_trim', 'duration_time']].head())
print(ride_sharing['duration_time'].mean())

     duration duration_trim  duration_time
0  12 minutes           12              12
1  24 minutes           24              24
2   8 minutes            8               8
3   4 minutes            4               4
4  11 minutes           11              11
11.389052795031056

### Data range constraints

How to deal with out of range data?

    - Dropping data, resikonya bisa kehilangan data essensial
    - Setting custom minimums and maximums column
    - Treat as missing and impute

In [ ]:
# Drop values using filtering
movies = movies[movies['avg_rating'] <= 5]

# Drop values using .drop()
movies.drop(movies[movies['avg_rating'] > 5].index, inplace = True)

# Asserts results
assert movies['avg_rating'].max() <= 5

# Convert avg_rating > 5 to 5
movies.loc[movies['avg_rating'] > 5, 'avg_rating'] = 5

In [ ]:
# Convert tire_sizes to integer
ride_sharing['tire_sizes'] = ride_sharing['tire_sizes'].astype('int')

# Set all values above 27 to 27
ride_sharing.loc[ride_sharing['tire_sizes'] > 27 , 'tire_sizes'] = 27

# Reconvert tire_sizes back to categorical
ride_sharing['tire_sizes'] = ride_sharing['tire_sizez'].astype('category')

# Print tire size description
print(ride_sharing['tire_sizes']._describe())

In [ ]:
# Convert ride_date to datetime
ride_sharing['ride_dt'] = pd.to_datetime(ride_sharing['ride_date'])

# Save today's date
today = dt.date.today()

# Set all in the future to today's date
ride_sharing.loc[ride_sharing['ride_dt'] > today, 'ride_dt'] = today

# Print maximum of ride_dt column
print(ride_sharing['ride_dt'].max())

### Uniqueness constraints

What are duplicate values?

    - ALl columns have the same values
    - Most columns have the same values

---------------------------------------------------------------
Why duplicate values happen?

    - Data entry & human error
    - Bugs and design errors
    - Join or merge errors

---------------------------------------------------------------
How to find duplicate rows?

    - Using .duplicated() method
    - subset: list of column names to check for duplication
    - keep: wheter to keep first('first), last('last), or all(False) duplicate values

---------------------------------------------------------------
How to treat duplicate rows?

    - Using .drop_duplicates() method
    - subset: list of column names to check for duplication
    - keep: wheter to keep first('first), last('last), or all(False) duplicate values
    - inplace: drop duplicated rows directly inside DataFrame without creatign new object(True)

---------------------------------------------------------------
How to treat duplicate rows?

    - Using .groupby() and .agg() method

In [ ]:
# Find duplicate values

# Print header
height_weight.head()

# Get duplicates across all columns
duplicates = height_weight.duplicated()
print(duplicates)

In [ ]:
# Column names to check for duplication 
column_names = ['first_name', 'last_name', 'address']
duplicates = height_weight.duplicated(subset = column_names, keep=False)

height_weight['duplicates'].sort_values(by='first_name')

In [ ]:
# Drop duplicates
height_weight.drop_duplicates(inplace= True)

In [ ]:
# Group by column names and produce statistical summaries
column_names = ['first_name', 'last_name', 'address']
summaries = {'height':'max', 'weight':'mean'}
height_weight = height_weight.groupby(by= column_names).agg(summaries).reset_index()

In [ ]:
# Find duplicates
duplicates = ride_sharing.duplicated(subset = 'ride_id', keep = False)

# Sort your duplicated rides
duplicated_rides = ride_sharing[duplicates].sort_values('ride_id')

# Print relevant columns
print(duplicated_rides[['ride_id','duration','user_birth_year']])

In [ ]:
# Drop complete duplicates from ride_sharing
ride_dup = ride_sharing.drop_duplicates()

# Create statistics dictionary for aggregation function
statistics = {'user_birth_year': 'min', 'duration': 'mean'}

# Group by ride_id and compute new statistics
ride_unique = ride_dup.groupby('ride_id').agg(statistics).reset_index()

# Find duplicated values again
duplicates = ride_unique.duplicated(subset = 'ride_id', keep = False)
duplicated_rides = ride_unique[duplicates == True]

# Assert duplicates are processed
assert duplicated_rides.shape[0] == 0

## 2. Text and categorical data problems

## 3. Advanced data problems

## 4. Record linkage